# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fzLCHitOUc9mcEd4tOxB3ZZXyUJxXz8
"""

!pip install streamlit
import pandas as pd
import streamlit as st
from sklearn.linear_model import LogisticRegression

st.title('Model Deployment: Logistic Regression')

st.sidebar.header('User Input Parameters')

def user_input_features():
    Pclass = st.sidebar.selectbox('Pclass',('1','2', '3'))
    Sex = st.sidebar.selectbox('Gender',('1','0'))
    Age = st.sidebar.number_input("Insert the Age")
    SibSp = st.sidebar.selectbox('Gender',('1','0','2', '3', '4', '5','8' ))
    Parch = st.sidebar.selectbox('Gender',('1','0','2', '3', '4', '5','6' ))
    Fare = st.sidebar.number_input("Insert Fare")
    Embarked = st.sidebar.selectbox('Embarked',('1','2', '3'))


    data = {'Pclass':Pclass,
            'Sex':Sex,
            'Age':Age,
            'SibSp':SibSp,
            'Parch':Parch,
            'Fare':Fare,
            'Embarked':Embarked
            }
    features = pd.DataFrame(data,index = [0])
    return features

df = user_input_features()
st.subheader('User Input parameters')
st.write(df)

claimants = pd.read_csv("/content/processed_data.csv")
#claimants.drop(["CASENUM"],inplace=True,axis = 1)
claimants = claimants.dropna()
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in claimants.select_dtypes(include='object'):
  # Convert the column to string type before applying LabelEncoder
  claimants[col] = claimants[col].astype(str)
  claimants[col] = le.fit_transform(claimants[col])

X = claimants.iloc[:,[1,2,3,4,5,6,7]]
Y = claimants.iloc[:,0]
clf = LogisticRegression()
clf.fit(X,Y)

prediction = clf.predict(df)  # Now df includes 'Parch' and 'SibSp'
prediction_proba = clf.predict_proba(df)

st.subheader('Predicted Result')
st.write('Yes' if prediction_proba[0][1] > 0.5 else 'No')

st.subheader('Prediction Probability')
st.write(prediction_proba)